apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: development-app
  template:
    metadata:
      labels:
        app: development-app
    spec:
      containers:
      - name: development-container
        image: europe-west4-docker.pkg.dev/qwiklabs-gcp-00-e3f8c2d9663c/my-repository/hello-cloudbuild-dev:v1.0
        ports:
        - containerPort: 8080
